# 
# Do not Edit! Generated by:
# spectacle version 0.14
# 
# >> macros
# << macros

Name:       mailcap
Summary:    Associates helper applications with particular file types
Version:    2.1.32
Release:    1
Group:      System/Base
License:    Public Domain
BuildArch:  noarch
URL:        http://www.redhat.com
Source0:    %{name}-%{version}.tar.gz
Source100:  mailcap.yaml

%description
The mailcap file is used by the metamail program.  Metamail reads the
mailcap file to determine how it should display non-text or multimedia
material.  Basically, mailcap associates a particular type of file
with a particular program that a mail agent or other program can call
in order to handle the file.

Mailcap should be installed to allow certain programs to be able to
handle non-text files.




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post


# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
mkdir -p $RPM_BUILD_ROOT%{_sysconfdir}
install -p -m 644 mailcap mime.types $RPM_BUILD_ROOT%{_sysconfdir}
mkdir -p $RPM_BUILD_ROOT%{_mandir}/man4
install -p -m 644 mailcap.4 $RPM_BUILD_ROOT%{_mandir}/man4


# << install post






%files
%defattr(-,root,root,-)
# >> files
%defattr(-,root,root)
%config(noreplace) %{_sysconfdir}/mailcap
%config(noreplace) %{_sysconfdir}/mime.types
%doc %{_mandir}/man4/mailcap.*
# << files


